services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5442:5432"
    env_file:
      - .env

  app_chat_chien:
    env_file:
      - .env
    volumes:
      - ${VOLUMES}/tmp:/tmp
    build:
      context: .       # la ou le dockerfile est (arborescence)
      dockerfile: Dockerfile.fastapi 
    image: chat-chien:latest  # Optionel : le nom
    ports:
      - "8000:8000"


volumes:
  postgres_data:
