name: CI

on:
  workflow_dispatch: # Pour le déclanchement manuel
  push:
    branches: [ main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: |
        docker compose up -d --build
    - name: Install les librairies de test
      run: |
        docker compose exec -T app_chat_chien pip install -r requirements/dev.txt

    - name: Run tests inside app container
      run: |
        docker compose exec -T app_chat_chien pytest

    - name: Shut down services
      if: always()
      run: docker compose down -v

